name: Checkout and setup
description: Checkout and setup
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version-file: '.nvmrc'
        cache: 'npm'
    - name: Install dependencies
      shell: sh
      run: npm install
